#!/usr/bin/env python
# -*- coding: UTF-8 -*-

## submit a task!

# 查询到当前所使用的全部的资源水平，需要，正在run 的任务的id 和 pid， 以及正在等待的任务的id
import sys
import os
#import getpass
import rutils
import time
from optparse import OptionParser,OptionGroup

def run_script(tasklist):
	lock = rutils.Lock()
	lock.get()
	tasks = open(rutils.get_installpath() + "/spool/tasks","r")
	outs = []
	for task in tasks:
		taskid,username,cwd,sndir,shcmd,askcpu,askmem,status,cpu_active, mem_active,time_active,max_cpu_active,max_mem_active,pid = task.rstrip("\n").split("\t")
		if taskid in tasklist: 
			if status == "R":
				rutils.killtasks(int(pid))
			status = "C"
		outs.append("\t".join([taskid,username,cwd,sndir,shcmd,askcpu,askmem,status,cpu_active, mem_active,time_active,max_cpu_active,max_mem_active,pid]))
	tasks.close()
	tasks = open(rutils.get_installpath() + "/spool/tasks","w")
	for line in outs:
		tasks.write(line+"\n")
	tasks.close()
	lock.release()
	return 0

if __name__ == "__main__":
	start_time = time.time()
	usage = "usage: %prog [options] task_id1 task_id2 ..."
	description = "Contact: Rong Zhengqin <rongzhengqin@basepedia.com>"
	parser = OptionParser(usage,version="%prog 0.1",description = description)
	Common_group = OptionGroup(parser,'Common Options')
	#Common_group.add_option('--run',dest='run',help='run server',action='store_true')
	#Common_group.add_option('--term',dest='term',help='kill server',action='store_true')
	parser.add_option_group(Common_group)
	
	(options, args) = parser.parse_args()
	if len(args) <1:
		parser.print_help()
		sys.exit(1)
	run_script(args[0:])
	sys.exit(0)

