#!/usr/bin/env python
# -*- coding: UTF-8 -*-

## submit a task!

# 查询到当前所使用的全部的资源水平，需要，正在run 的任务的id 和 pid， 以及正在等待的任务的id
import sys
import os
import getpass
import rutils
import time
from optparse import OptionParser,OptionGroup
import getpass
import datetime 
def run_script(flag):
	user = getpass.getuser()
	lock = rutils.Lock()
	lock.get()
	
	fmt = "%-6s\t%-10s\t%-15s\t%-6s\t%-6s\t%-4s\t%-8s\t%-8s\t%-12s\t%-8s\t%-8s\n"
	tasks = open(rutils.get_installpath() + "/spool/tasks","r")
	sys.stdout.write(fmt%("Task","User","CMD","CPUs","MEMs","STAT","A_CPUs","A_MEMs","A_Time","M_CPUs","M_MEMs"))
	for task in tasks:
		taskid,username,cwd,sndir,shcmd,askcpu,askmem,status,cpu_active, mem_active,time_active,max_cpu_active,max_mem_active,pid = task.rstrip("\n").split("\t")
		if user != username and flag:continue
		else:
			mem_active = rutils.mem_print(int(mem_active))
			time_active= str(datetime.timedelta(seconds=float(time_active))) 
			max_mem_active = rutils.mem_print(int(max_mem_active))
			askmem = rutils.mem_print(int(askmem))
			sys.stdout.write(fmt%(taskid,username,shcmd,askcpu,askmem,status,cpu_active,mem_active,time_active,max_cpu_active,max_mem_active))
	tasks.close()
	lock.release()
	return 0


if __name__ == "__main__":
	start_time = time.time()
	usage = "usage: %prog [options]"
	description = "Contact: Rong Zhengqin <rongzhengqin@basepedia.com>"
	parser = OptionParser(usage,version="%prog 0.1",description = description)
	Common_group = OptionGroup(parser,'Common Options')
	Common_group.add_option('-a',dest='all',help='show tasks of all users',action='store_true')
	#Common_group.add_option('-f',dest='al`l',help='show tasks of all users',action='store_true')
	parser.add_option_group(Common_group)
	
	(options, args) = parser.parse_args()
	if not options:
		parser.print_help()
		sys.exit(1)
		
	if options.all: flag = 1
	else: flag = 0
	run_script(flag)
	sys.exit(0)

