#!/usr/bin/env python
import sys
import os
import subprocess
### 

# homedir = "/home"

ncpus = 46
nmem  = 245000000 # 245 G
jobstart = 0
maxjob = 999999


installpath = sys.argv[1] # workdir for the service 
#status,users = subprocess.getstatusoutput("ls %s"%homedir)

#users = users.strip().split()
cmds = ["mkdir -p %s/spool/config"%installpath]
cmds.append("rm -f %s/spool/tasks && touch  %s/spool/tasks && echo 0 > %s/spool/taskid && touch  %s/spool/tasks.bak && echo 0 > %s/spool/taskid.bak && touch %s/spool/config/lockfile"%(installpath,installpath,installpath,installpath,installpath,installpath))
#for user in users:
#	cmds.append("mkdir -p %s/%s"%(installpath,user)) 
if os.system(" && ".join(cmds)) == 0:
	sys.stderr.write("Success!\n")
	sys.stderr.write("  Config path: %s/spool/config\n\n"%os.path.abspath(installpath))
	#sys.stderr.write("  Users created:\n     %s\n"%",".join(users))

jobinfo_fn = "%s/spool/config/jobinfo"%installpath
if not os.path.isfile(jobinfo_fn):
	f = open(jobinfo_fn,"w")
	f.write("%d\n%d\n%d\n"%(ncpus,nmem,maxjob))
	f.close()
sys.exit(0)


